replicaCount: 1

image:
  repository: nginx
  tag: "1.16"
  pullPolicy: IfNotPresent

container:
  name: app

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"
